language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - export PATH=$HOME/build/dizak/headnode_notifier:$PATH
  - alias diff='diff --ignore-blank-lines --ignore-trailing-space'

script:
  - headnode_notifier.py -h > test_help.log
  - diff test_data/logs/ref_help.log test_help.log
  - echo $test_passwd

notifications:
  email:
    on_success: never
    on_failure: always
